version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    command: sh -c "/wait; sleep 5; alembic upgrade head; fastapi run app/src/main.py"
    ports:
      - "8000:8000"